// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "King tower red":return img`
................................
................................
................................
................................
.......ffffffffffffffffffff.....
.......fdddddd5d5d5dddddddf.....
.......fdddddd22222dddddddf.....
.......fddddddeeeeedddddddf.....
......222dddddefefedddddd222....
......222dddddeeeeedddddd222....
......222dddddefffedddddd222....
......222dddddeeeeedddddd222....
......222dddded222deddddd222....
......2fdddddde222edddddddf2....
......2fddddddd222ddddddddf2....
......2ffffffffffffffffffff2....
......2fddddddddddddddddddf2....
......2fdd555dd5555dd555ddf2....
......2fdd5555d5555d5555ddf2....
......2fcc5555d5555d5555ccf2....
......2fdc55555555555555ddf2....
.......fdc55555555555555ddf.....
.......fdc55555555555555ddf.....
.......fcc55555555555555ccf.....
.......fddcdddddddcdddddddf.....
.......fddcdddddddcdddddddf.....
.......fddcdddddddcdddddddf.....
.......fccccccccccccccccccf.....
.......fddddcdddddddcdddddf.....
.......fddddcdddddddcdddddf.....
.......fddddcdddddddcdddddf.....
.......ffffffffffffffffffff.....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
